name: Cleanup Stale Branches

permissions:
  issues: write
  contents: write

on:
  workflow_dispatch:

jobs:
  cleanup-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Stale Branches
        uses: cbrgm/cleanup-stale-branches-action@v1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          ignore-branches: "main, master, develop, qa, staging, , *main*, *master*"
          #ignore-prefixes: "feature/,bugfix/"
          last-commit-age-days: 90
          dry-run: false
          rate-limit: true