name: remove_stale_branches

on:
  workflow_dispatch:
    
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v5.0.0
      with:
        repo-token:  ${{ github.token }}
        days-before-stale: 45
        days-before-delete: 90
        max-issues: 5
        comment-updates: false
        stale-branch-label: 'stale branch :wastebasket:'
        compare-branches: save
        branches-filter-regex: '^(?!.(develop|qa|stage|staging|main|master)).$'
        pr-check: true
        dry-run: true