name: Delete Old Branches
permissions:
  contents: write
on:
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  delete-old-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install jq and GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo apt-get install -y gh

      - name: Delete branches older than 12 months
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the date 12 months ago in ISO format
          ONE_YEAR_AGO=$(date -d '12 months ago' --utc +%Y-%m-%dT%H:%M:%SZ)
          echo "Deleting branches with last commit before: $ONE_YEAR_AGO"
          
          # Initialize a file to store branches that will be deleted
          > branches_to_delete.txt
          
          # Fetch all branches and filter by last commit date
          gh api -X GET "repos/$REPO/branches" --paginate \
            | jq -r '.[] | @base64' | while read branch_data; do
                # Decode JSON data for each branch
                branch_json=$(echo "$branch_data" | base64 --decode)
                branch_name=$(echo "$branch_json" | jq -r '.name')
                last_commit_date=$(echo "$branch_json" | jq -r '.commit.commit.author.date')

                # Skip protected branches
                if [[ "$branch_name" == "main" || "$branch_name" == "master" || "$branch_name" == "develop" || "$branch_name" == "qa" || "$branch_name" == "staging" ]]; then
                  echo "Skipping protected branch: $branch_name"
                  continue
                fi

                # Compare last commit date with one year ago
                if [[ "$last_commit_date" < "$ONE_YEAR_AGO" ]]; then
                  # Log branch to file and delete it
                  echo "$branch_name" >> branches_to_delete.txt
                  echo "Deleting branch: $branch_name"
                  # gh api -X DELETE "repos/$REPO/git/refs/heads/$branch_name"
                else
                  echo "Keeping branch: $branch_name (Last commit: $last_commit_date)"
                fi
              done

      - name: Upload deleted branches list
        uses: actions/upload-artifact@v4
        with:
          name: deleted-branches
          path: branches_to_delete.txt
