name: remove_stale_branches

permissions:
  contents: write

on: workflow_dispatch

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v1.6.0
        with:
          github-token: $ {{ github.token }}
          dry-run: true # Check out the console output before setting this to false
          ignore-branches-with-open-prs: true
          exempt-organization: "acme-inc"
          exempt-authors-regex: ^(main|master|develop|qa|staging)$
          days-before-branch-stale: 90
          days-before-branch-delete: 0